# 指定基础镜像
FROM ubuntu:latest

# 更新软件源并安装软件包
RUN apt-get update && \
    apt-get install -y \
    vim \
    python3 \
    python3-pip

# 拷贝本地文件到镜像中
COPY . /app

# 设置工作目录
WORKDIR /app

# 启动命令
CMD ["bash"]